runtime: nodejs16

instance_class: F4

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'cracking-snacks'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: 'RYJ%vi~h6<0bJP]$'
  INSTANCE_CONNECTION_NAME: 'vocal-partition-333715:us-central1:nemesis'

beta_settings:
  cloud_sql_instances: 'vocal-partition-333715:us-central1:nemesis'
